### ISSUE TITLE
How to set generation_config

### ISSUE THREAD

**Issue by lwpyh** [meetdavidwan/crg#1]
Hi there,

Thank you for this great work, just want to know how to set the generation_config to trigger CFG when `model_kwargs_blackout` is supplied? 

I have set generation_config=None or generation_config=model.generation_config, but both of them cannot trigger CFG, could you help me to address it?

Best,
Jian

**Comment by meetdavidwan** [comment]
Thanks for your interest in the work!

Could you provide more information on what arguments you include for `model_kwargs_blackout`? How the code works should be just a single `model_kwargs_blackout` with some of the inputs with suffix `_blackout`. To trigger CFG, you would need (1) have the correct inputs similar to [here](https://github.com/meetdavidwan/crg/blob/1fa4aef5df11f6c2899fdda440fdbe465c8a2327/model_vqa_contrastive.py#L117) which are processed in [here](https://github.com/meetdavidwan/crg/blob/1fa4aef5df11f6c2899fdda440fdbe465c8a2327/contrastive_generate.py#L632), and (2) only have greedy decoding option (i.e. `sample=false, num_beams=1`). If you want to do sample, feel free to change the `contrastive_generate according.py` similar to how I changed `greedy_decoding` function.

Let me know if you have any further questions.

**Comment by lwpyh** [comment]
Thank you for your kind reply, I have addressed this issue, I think I have set the wrong setting since I am trying to modify the code  on other decoding options. Thank you for your kindly reply.
